# Generated by Django 6.0.6 on 2026-06-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choic_poll',
            new_name='choice_poll',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choic_text',
            new_name='choice_set',
        ),
    ]
